# Site settings
title: Shoreline Media Marketing on Github
email: team@shorelinemedianj.com
description: Shoreline Media Marketing provides full service web marketing including web design and development, SEO, Content Strategies, Social Media Marketing, Pay-Per-Click Ad Management and more. Visit http://www.shorelinemediamarketing.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shoreline-media.github.io" # the base hostname & protocol for your site
twitter_username: shorelinenj
github_username:  shoreline-media
permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock', 'bower_components', 'node_modules']

prose:
  rooturl: '_posts'
  siteurl: 'http://shoreline-media.github.io/'
  relativeLinks: 'http://shoreline-media.github.io/links.jsonp'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - Gemfile
    - Gemfile.lock
  metadata:
    _posts:
      - name: "category"
        field:
          element: "text"
          value: "blog"
      - name: "layout"
        field:
          element: "text"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "media"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Best Practice"
              value: "best-practice"
            - name: "Wordpress"
              value: "wordpress"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""

# Build settings
markdown: rdiscount
